# Generated by Django 2.2.4 on 2019-08-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('fct_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fct_nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('prs_rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prs_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('prs_telefono', models.BigIntegerField(blank=True, null=True)),
                ('fct_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intranet.Facultad')),
            ],
        ),
    ]
