# Generated by Django 2.2.4 on 2019-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_persona_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('usu_password', models.BigIntegerField(blank=True)),
                ('per_id', models.BigIntegerField(blank=True)),
                ('usu_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
